// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mXn4lwgVKiBLsjS8d_3BxZFIrO8C_qU',
    appId: '1:1066365657948:web:9439a4a890583beb9d9799',
    messagingSenderId: '1066365657948',
    projectId: 'flutter-reddit-cd9d1',
    authDomain: 'flutter-reddit-cd9d1.firebaseapp.com',
    storageBucket: 'flutter-reddit-cd9d1.appspot.com',
    measurementId: 'G-DGFE9BDC1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4W3BQicxH8lw60bm3irH7DHCZQq9B7U',
    appId: '1:1066365657948:android:707d21f708d3c1479d9799',
    messagingSenderId: '1066365657948',
    projectId: 'flutter-reddit-cd9d1',
    storageBucket: 'flutter-reddit-cd9d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUZorcwdRVD1OF6K6vxD0ck4_D2q6UYg',
    appId: '1:1066365657948:ios:9115236531ebeeb29d9799',
    messagingSenderId: '1066365657948',
    projectId: 'flutter-reddit-cd9d1',
    storageBucket: 'flutter-reddit-cd9d1.appspot.com',
    iosClientId: '1066365657948-34t1djknoktq4ac7lcuu0u12npksv1em.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIUZorcwdRVD1OF6K6vxD0ck4_D2q6UYg',
    appId: '1:1066365657948:ios:5aa574178f5a59719d9799',
    messagingSenderId: '1066365657948',
    projectId: 'flutter-reddit-cd9d1',
    storageBucket: 'flutter-reddit-cd9d1.appspot.com',
    iosClientId: '1066365657948-ree0nb30njuj9klkhu8n0bara5un2nsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedditClone.RunnerTests',
  );
}
